version: '2'
services:
  redcap:
    image: 123andy/redcap-lamp
    ports:
      - "80:80"
      - "3306:3306"
    volumes:
      - "/Users/andy123/Documents/Docker/redcap_www:/redcap_webroot"
      - "/Users/andy123/Documents/Docker/redcap_mysql:/var/lib/mysql"
    links:
      - "mailhog:mailhog"
    depends_on:
      - redcap
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "81:8025"